const wtf = require('/Users/spencer/mountain/wtf_wikipedia/')

let arr = [
  'Mercier, Quebec',
  'Métabetchouan–Lac-à-la-Croix',
  'Métis-sur-Mer, Quebec',
  'Mirabel, Quebec',
  'Mont-Joli',
  'Mont-Laurier',
  'Montmagny, Quebec',
  'Montreal',
  'Montreal West, Quebec',
  'Montréal-Est, Quebec',
  'Mont-Saint-Hilaire, Quebec',
  'Mont-Tremblant, Quebec',
  'Mount Royal, Quebec',
  'Murdochville, Quebec',
  'Neuville, Quebec',
  'New Richmond, Quebec',
  'Nicolet, Quebec',
  'Normandin, Quebec',
  "Notre-Dame-de-l'Île-Perrot, Quebec",
  'Notre-Dame-des-Prairies, Quebec',
  'Otterburn Park, Quebec',
  'Paspébiac',
  'Percé, Quebec',
  'Pincourt, Quebec',
  'Plessisville, Quebec',
  'Pohénégamook',
  'Pointe-Claire',
  'Pont-Rouge',
  'Port-Cartier',
  'Portneuf, Quebec',
  'Prévost, Quebec',
  'Princeville, Quebec',
  'Quebec City',
  'Repentigny, Quebec',
  'Richelieu, Quebec',
  'Richmond, Quebec',
  'Rimouski',
  'Rivière-du-Loup',
  'Rivière-Rouge',
  'Roberval, Quebec',
  'Rosemère, Quebec',
  'Rouyn-Noranda',
  'Saguenay, Quebec',
  'Saint-Augustin-de-Desmaures',
  'Saint-Basile, Quebec',
  'Saint-Basile-le-Grand, Quebec',
  'Saint-Bruno-de-Montarville',
  'Saint-Césaire, Quebec',
  'Saint-Colomban, Quebec',
  'Saint-Constant, Quebec',
  'Sainte-Adèle, Quebec',
  'Sainte-Agathe-des-Monts',
  'Sainte-Anne-de-Beaupré',
  'Sainte-Anne-de-Bellevue, Quebec',
  'Sainte-Anne-des-Monts, Quebec',
  'Sainte-Anne-des-Plaines, Quebec',
  'Sainte-Catherine, Quebec',
  'Sainte-Catherine-de-la-Jacques-Cartier',
  'Sainte-Julie, Quebec',
  'Sainte-Marguerite-du-Lac-Masson, Quebec',
  'Sainte-Marie, Quebec',
  'Sainte-Marthe-sur-le-Lac, Quebec',
  'Sainte-Thérèse, Quebec',
  'Saint-Eustache, Quebec',
  'Saint-Félicien, Quebec',
  'Saint-Gabriel, Quebec',
  'Saint-Georges, Quebec',
  'Saint-Hyacinthe, Quebec',
  'Saint-Jean-sur-Richelieu, Quebec',
  'Saint-Jérôme, Quebec',
  'Saint-Joseph-de-Beauce, Quebec',
  'Saint-Joseph-de-Sorel, Quebec',
  'Saint-Lambert, Quebec',
  'Saint-Lazare, Quebec',
  'Saint-Lin-Laurentides',
  'Saint-Marc-des-Carrières',
  'Saint-Ours, Quebec',
  'Saint-Pamphile, Quebec',
  'Saint-Pascal, Quebec',
  'Saint-Pie, Quebec',
  'Saint-Raymond, Quebec',
  'Saint-Rémi, Quebec',
  'Saint-Sauveur, Quebec',
  'Saint-Tite, Quebec',
  'Salaberry-de-Valleyfield',
  'Schefferville, Quebec',
  'Scotstown, Quebec',
  'Senneterre, Quebec',
  'Sept-Îles, Quebec',
  'Shawinigan',
  'Sherbrooke',
  'Sorel-Tracy',
  'Stanstead, Quebec',
  'Sutton, Quebec',
  'Témiscaming, Quebec',
  'Témiscouata-sur-le-Lac, Quebec',
  'Terrebonne, Quebec',
  'Thetford Mines',
  'Thurso, Quebec',
  'Trois-Pistoles, Quebec',
  'Trois-Rivières',
  'Valcourt (city)',
  "Val-d'Or",
  'Varennes, Quebec',
  'Vaudreuil-Dorion',
  'Victoriaville',
  'Ville-Marie, Quebec',
  'Warwick, Quebec',
  'Waterloo, Quebec',
  'Waterville, Quebec',
  'Westmount, Quebec',
  'Windsor, Quebec'
]

wtf.fetch(arr, (err, docs) => {
  let places = docs.reduce((h, doc) => {
    let coord = (doc.templates('coord') || [])[0] || {}
    console.log(coord)
    h[doc.title()] = [coord.lat, coord.lon]
    return h
  }, {})
  console.log(JSON.stringify(places, null, 2))
})
